name: ibkr-web-api
services:
  ibkr-web-api:
    build: .
    image: ibkr-web-api
    container_name: ibkr-web-api
    environment:
      IBKR_ACCOUNT_ID: "U13313113"
    ports:
      - "5055:5055"
      - "5056:5056"
    volumes:
      - ./webapp:/app/webapp